defaults:
  - train
  - _self_

batch_size: 256

mesh:
  _target_: pinnstf2.data.PointCloud
  root_dir: ${paths.data_dir}
  read_data_fn: ???

train_datasets:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      collection_points:
        - f_u
        - f_v
  - dirichlet_boundary_condition:
      _target_: pinnstf2.data.DirichletBoundaryCondition
      _partial_: true
      solution:
        - u
        - v
  - outlet_boundary_condition:
      _target_: pinnstf2.data.PressureBoundaryCondition
      _partial_: true
      solution:
        - p
  - inlet_boundary_condition:
      _target_: pinnstf2.data.InletBoundaryCondition
      _partial_: true
      solution:
        - u
        - v

val_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      solution:
        - u
        - v
        - p

test_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      idx_t: 1
      solution:
        - u
        - v
        - p

pred_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      idx_t: 1
      solution:
        - u
        - v
        - p

net:
  _target_: pinnstf2.models.FCN
  layers: [3, 20, 20, 20, 20, 20, 20, 20, 20, 2]
  output_names:
    - psi
    - p

model:
  loss_fn: mse
  amp: false

trainer:
  max_epochs: 100000
  check_val_every_n_epoch: 5000

train: true
test: false
val: false

optimized_metric:
  error:
    - u
    - v
    - p

plotting:
  _target_: pinnstf2.utils.plot_navier_stokes
  _partial_: true

task_name: aneurysm3D

hydra:
  searchpath:
    - pkg://pinnstf2/conf