defaults:
  - train
  - _self_

batch_size: 10000

mesh:
  _target_: pinnstf2.data.PointCloud
  root_dir: ${paths.data_dir}
  read_data_fn: ???

train_datasets:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      solution:
        - c
      collection_points:
        - e1
        - e2
        - e3
        - e4
        - e5
  - dirichlet_boundary_condition:
      _target_: pinnstf2.data.DirichletBoundaryCondition
      _partial_: true
      solution:
        - u
        - v
        - w
  - inlet_boundary_condition:
      _target_: pinnstf2.data.InletBoundaryCondition
      _partial_: true
      solution:
        - u
        - v
        - w
        - c 

val_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      solution:
        - c

test_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      idx_t: 1
      solution:
        - c

pred_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      idx_t: 1
      solution:
        - c
        - u
        - v
        - w
        - p

net:
  _target_: pinnstf2.models.NetHFM
  layers: [4, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 5]
  output_names:
    - c
    - u
    - v
    - w
    - p

model:
  loss_fn: mse
  extra_variables:
    l1: 161.06504
    l2: 128.5464
  

trainer:
  max_epochs: 1000000
  check_val_every_n_epoch: 1000

train: true
test: false
val: true

optimized_metric:
  error:
    - c
    - u
    - v
    - w
    - p
  extra_variables:
    - l1
    - l2

plotting:
  _target_: pinnstf2.utils.plot_navier_stokes
  _partial_: true

task_name: aneurysm3D

hydra:
  searchpath:
    - pkg://pinnstf2/conf