defaults:
  - train
  - _self_

n_train: 5_000

mesh:
  _target_: pinnstf2.data.PointCloud
  root_dir: ${paths.data_dir}
  read_data_fn: ???

train_datasets:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      num_sample: ${n_train}
      solution:
        - u
        - v
      collection_points:
        - f_u
        - f_v

val_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      solution:
        - u
        - v
        - p

pred_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      idx_t: 100
      solution:
        - u
        - v
        - p

net:
  _target_: pinnstf2.models.FCN
  layers: [3, 20, 20, 20, 20, 20, 20, 20, 20, 2]
  output_names:
    - psi
    - p

model:
  extra_variables:
    l1: 0.0
    l2: 0.0

trainer:
  max_epochs: 100000
  check_val_every_n_epoch: 101

train: true
val: true
test: false
optimized_metric:
  error:
    - u
    - v
    - p
  extra_variables:
    - l1
    - l2

task_name: navier_stokes

hydra:
  searchpath:
    - pkg://pinnstf2/conf
